name: roome
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.8.3
  conditional_builder_null_safety: ^0.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  reusable_components:
    git:
      url: https://github.com/ahmedghaly15/Reusable-Components-Package
  shared_preferences: ^2.2.0
  google_sign_in: ^6.1.4
  image_picker: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/introduction/
    - assets/icon/

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart
  field_prefix:
